# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d3de5d295ab5fc4dae8caad614ffe6fb1bc115ecd87a512465d358e42a0560ebe7d62ab099d0274c8c246568bef5213e513b88b89a9fc42ac99d17ea5bb5bb0

test:
  secret_key_base: 1c685051a9a7a83a3cc9ebd3d52b853ac8d3272dbafedefe3f16a9eb522e040149b9070fbc70f3994dfb245b78cd9253ff6af45becac416accadd3745c236351

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
